### PR TITLE
Movement

### PR DESCRIPTION
**Pull request by camronCollinsworth**
This turned into a bit of a mess and I am very sorry for the horrendous formatting and git documentation / traceability. I really need to improve that in the future. 

Changes 

- [x] AI has a basic reaction time system implemented. When reacting to similar or the same stimulus, their reaction time is near instant. When reacting to a new stimulus, the reaction time is higher. 

- [x] AI can now move towards and collect power ups

- [x] AI no longer drive endlessly in circles when near obstacles

- [x] AI no longer drive endlessly in circles when in combat with the player

- [x] AI perform basic swerving evasive maneuvers when traversing to players

- [x] AI will now prioritize getting power ups when there are no nearby runners

References Stories:

#251 - implement ai runner reaction time 

#152 - AI move toward power-ups

#241 - AI prioritize power ups

Work logs:

11/3 Worked for 1.5 hours on AI movement. AI actors no longer move in circles when there is a nearby wall. Spent the majority of the time reviewing code from the previous semesters and testing various solutions.

11/19 Worked 1.5 hours on ai movement. Implemented pretty much all of the functionality needed to move towards powerups

11/20 Worked .75 minutes with Andrew and tavi on movement. Currently facing issues with the class hierarchy of powerups.

11/21 Worked 1.25 hours on movement. Fixed the behavior of AI runners driving in circles while in combat with the player.

11/22 worked for 1.5 hours on movement. 30 minutes of which was with Nathan. Still no clue on movement towards powerups

11/30 Worked 3.75 hours on ai movement. Finally got move towards powerup implemented with the help of Andrew. Functional requirements are now met.

### CODE REVIEW

**Review by timblegoorn — APPROVED** [review]
Great work!

**Review by quinnshultz — APPROVED** [review]
Wooooo!

**Review by dameebsu — APPROVED** [review]
Figured you should have 3 approvals for this one!

**Review by Nathan-Turtleduck — APPROVED** [review]
You get an extra approval for the excellent work done!

**Pull request merged**
